export const metadata = {
	title: "Kristofer",
	description: "Generated by Kristofer Rossoni Krindges",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<link rel="preconnect" href="https://fonts.gstatic.com" />
			<link
				href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
				rel="stylesheet"
			/>
			<link rel="icon" href="%PUBLIC_URL%/kristofer.ico" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<meta
				name="PortifolioKristoferRK"
				content="Created by Kristofer Krindges"
			/>
			<body>{children}</body>
		</html>
	);
}
